In [2]:
import numpy as np

D1 = np.array([1, 2, 3])

D2 = np.array([
        [1, 2, 3],
        [4, 5, 6]
    ])
                
D3 = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
     
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
])

In [5]:
print(D1.shape) 
print(D2.shape)
print(D3.shape)

(3,)
(2, 3)
(2, 3, 3)


In [6]:
print(D1.ndim) 
print(D2.ndim)
print(D3.ndim)

1
2
3


In [7]:
print(D1.dtype) 
print(D2.dtype)
print(D3.dtype)

int64
int64
int64


In [8]:
print(D1.size) 
print(D2.size)
print(D3.size)

3
6
18


In [9]:
print(type(D1)) 
print(type(D2))
print(type(D3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
test = np.ones((10,2,5))
test

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [20]:
random_array = np.random.randint(9, 11, size=(7, 2))
random_array

array([[ 9, 10],
       [10, 10],
       [ 9, 10],
       [10, 10],
       [ 9,  9],
       [10,  9],
       [10, 10]])

In [23]:
array = np.random.randint(1, 10, size=(3, 7))

print(array)
print(array[0])

[[2 6 1 7 6 6 6]
 [6 9 1 5 2 1 9]
 [7 6 6 3 4 4 8]]
[2 6 1 7 6 6 6]


In [26]:
temp1 = np.random.randint(0,10, size=(3,5))
temp2 = np.ones((3,5))

temp1
temp2

print(temp1 + temp2)

[[ 2.  8.  3.  5.  7.]
 [ 3.  1. 10.  9.  7.]
 [ 5.  8.  3.  3.  6.]]
